### ISSUE TITLE
Invalid request header sent to errbit

### ISSUE THREAD

**Issue by abasourdi** [WheresWardy/airbrake-proxy#4]
When sending manually a request to errbit throught xml, I get the following error:

14 Oct 09:29:27 - XML object returned from myhost:80 is invalid (Error: xml2js parse error: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: N); response: Need a data params in GET or raw post data

This is due to a missing:
				'Content-Length': data.length,

in the airbrakeRequestOptions. Headers need to be:

			headers: {
				'Content-Type': "text/xml",
				'Connection': "close",
				'Content-Length': data.length,
			},

**Comment by WheresWardy** [comment]
Fix has been merged
